#server:
#  port: 8033
#
#datasource:
#    druid:
#      #jdbc配置
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf8
#      username: root
#      password: 123456
#
#      #druid连接池配置
#      initial-size: 5
#      max-active: 20
#      min-idle: 5
#      max-wait: 60000 # 配置获取连接等待超时的时间
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      validation-query: SELECT 1 FROM DUAL
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
#      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#
#      web-stat-filter.enabled: true #是否启用StatFilter默认值true
#      web-stat-filter.url-pattern: /*
#      web-stat-filter.exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#      web-stat-filter.session-stat-enable: true
#
#      #配置_StatViewServlet配置
#      stat-view-servlet.enabled: true #是否启用StatViewServlet默认值true
#      stat-view-servlet.url-pattern: /druid/*
#      stat-view-servlet.reset-enable: true
#      stat-view-servlet.login-username: admin
#      stat-view-servlet.login-password: admin
